<?php


namespace App\Http\Requests;


use Illuminate\Foundation\Http\FormRequest;

class addHousehold extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
    //validation rules
            'Name'=>'required',
            'Address'=>'required',
            'City'=>'required'
        ];
    }
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
